1) Find what ammounts a Customer was charged

SELECT Customer.nfc_id, Customer.first_name, Customer.last_name, Service.service_descr, Charge.ammount FROM Customer, Receive, Service, Charge WHERE Customer.nfc_id=1 AND Customer.nfc_id=Receive.nfc_id AND Receive.service_id=Service.service_id AND Service.service_id=Charge.service_id AND Charge.charge_time=Receive.charge_time AND Customer.nfc_id=Charge.nfc_id

2) Find which Customers used a Service, their information and what they were charged for it

SELECT DISTINCT Customer.nfc_id, Customer.first_name, Customer.last_name, Customer.birthdate, Email.email_address, Phone.phone_number, Service.service_descr, Charge.charge_time, Charge.charge_descr, Charge.ammount FROM Customer, Email, Phone, Receive, Service, Charge WHERE Customer.nfc_id=Email.nfc_id AND Customer.nfc_id=Phone.nfc_id AND Customer.nfc_id=Receive.nfc_id AND Receive.service_id=Service.service_id AND Service.service_id=Charge.service_id AND Receive.charge_time=Charge.charge_time AND Customer.nfc_id=Charge.nfc_id AND Charge.service_id='G4'

3) Find which Customers used a Service and show information about them, the Service, the Space and their Charge for their Service

SELECT DISTINCT Customer.nfc_id, Customer.first_name, Customer.last_name, Customer.birthdate, Email.email_address, Phone.phone_number, Service.service_descr, Charge.charge_time, Charge.charge_descr, Charge.ammount, Space.space_name, Space.space_descr FROM Customer, Email, Phone, Receive, Service, Charge, Provided, Space WHERE Customer.nfc_id=Email.nfc_id AND Customer.nfc_id=Phone.nfc_id AND Customer.nfc_id=Receive.nfc_id AND Receive.service_id=Service.service_id AND Service.service_id=Charge.service_id AND Receive.charge_time=Charge.charge_time AND Service.service_id=Provided.service_id AND Provided.space_id=Space.space_id AND Customer.nfc_id=Charge.nfc_id AND Charge.service_id='G4'

4) Find which Customers used a Service and show information about them, the Service, the Space and their Charge and Subscription information for their Service

SELECT DISTINCT Customer.nfc_id, Customer.first_name, Customer.last_name, Customer.birthdate, Email.email_address, Phone.phone_number, Service.service_descr, Charge.charge_time, Charge.charge_descr, Charge.ammount, Space.space_name, Space.space_descr, Subscribe.subscr_time FROM Customer, Email, Phone, Receive, Service, Charge, Provided, Space, Subscription, Subscribe WHERE Customer.nfc_id=Email.nfc_id AND Customer.nfc_id=Phone.nfc_id AND Customer.nfc_id=Receive.nfc_id AND Receive.service_id=Service.service_id AND Service.service_id=Charge.service_id AND Receive.charge_time=Charge.charge_time AND Service.service_id=Provided.service_id AND Provided.space_id=Space.space_id AND Service.service_id=Subscription.subscr_id AND Subscription.subscr_id=Subscribe.subscr_id and Subscribe.nfc_id=Customer.nfc_id AND Customer.nfc_id=Charge.nfc_id AND Charge.service_id='G4'

5) Find which Customers used a Service and show information about them, the Service, the Space and their Charge and Subscription information for their Service, as well as their Visiting Times

SELECT DISTINCT Customer.nfc_id, Customer.first_name, Customer.last_name, Customer.birthdate, Email.email_address, Phone.phone_number, Service.service_descr, Charge.charge_time, Charge.charge_descr, Charge.ammount, Space.space_name, Space.space_descr, Subscribe.subscr_time, Visit.entry_time, Visit.exit_time FROM Customer, Email, Phone, Receive, Service, Charge, Provided, Space, Subscription, Subscribe, Visit WHERE Customer.nfc_id=Email.nfc_id AND Customer.nfc_id=Phone.nfc_id AND Customer.nfc_id=Receive.nfc_id AND Receive.service_id=Service.service_id AND Service.service_id=Charge.service_id AND Receive.charge_time=Charge.charge_time AND Service.service_id=Provided.service_id AND Provided.space_id=Space.space_id AND Service.service_id=Subscription.subscr_id AND Subscription.subscr_id=Subscribe.subscr_id and Subscribe.nfc_id=Customer.nfc_id AND Customer.nfc_id=Visit.nfc_id AND Visit.space_id=Space.space_id AND Customer.nfc_id=Charge.nfc_id AND Charge.service_id='W3'